language: chinese  #english  or chinese
auto_dispatch: true
observation_image: true
config_directory: demo

alarm:
  short_time: 8 #超出此时间后告警
  long_time: 20  #超出此时间后失败

products:
- code: A
  num: 3
- code: B
  num: 2

#max_x: 32  #加工槽逻辑上排成一排，最远的偏移是多少个单元格

fps: 60
tile_size: 48      # 绘图单位方格的像数值
screen_columns: 20 # 屏幕有多少列单位方格

