SHOW_JOB_LIST: true
EPS: 0.01
FPS: 24
CELL_SIZE: 100
ROWS: 6
COLS: 8
INFO_COLS: 6
MAX_JOBS: 10
FIRST_GROUP_MAX_JOBS: 3
MAX_LOCK_TIME: 10
MIN_WAIT_TIME: 6
NOTIFY_BEFORE_FINISH: 20
SAFE_CRANE_DISTANCE: 2
H_TOP: 0.9
H_LOW: 0.4
SLOT_COLORS:
  S: [200,200,200]
  DN: [105,55,255]
  DT: [255,255,0]
  SX: [5,55,255]
  T: [100,100,100]
  E: [50,50,50]
PROC_COLORS:
  P1: [255,0,0]
  P2: [0,255,0]
  P3: [0,0,255]