START: 1
END: 23
CRANES:
- !!python/object/new:epsim.crane_info [ 1, H1, 1, 0.5, 1, 13, 1, 2]
- !!python/object/new:epsim.crane_info [ 1, H2, 1, 0.5, 3, 15, 15, 2]
- !!python/object/new:epsim.crane_info [ 2, H3, 1, 0.5, 16, 23, 16, 2]
JOBS: {P1: 2,P2: 3}
PROCS:
  P1:
  - !!python/object/new:epsim.op_info [S, 1, 0]
  - !!python/object/new:epsim.op_info [DN, 100, 5]
  - !!python/object/new:epsim.op_info [SX, 40, 2]
  - !!python/object/new:epsim.op_info [T, 1, 0]
  - !!python/object/new:epsim.op_info [SX, 40, 2]
  - !!python/object/new:epsim.op_info [E, 1, 0]
  P2:
  - !!python/object/new:epsim.op_info [S, 1, 0]
  - !!python/object/new:epsim.op_info [DN, 160, 5]
  - !!python/object/new:epsim.op_info [SX, 100, 2]
  - !!python/object/new:epsim.op_info [DT, 120, 5]
  - !!python/object/new:epsim.op_info [T, 1, 0]
  - !!python/object/new:epsim.op_info [SX, 80, 2]
  - !!python/object/new:epsim.op_info [E, 1, 0]

SLOTS:
  S:
  - !!python/object/new:epsim.slot_info [1, S, 1]
  DN:
  - !!python/object/new:epsim.slot_info [1, DN1, 3]
  - !!python/object/new:epsim.slot_info [1, DN2, 4]
  T:
  - !!python/object/new:epsim.slot_info [1,T1, 15]
  - !!python/object/new:epsim.slot_info [2,T2, 16]
  DT:
  - !!python/object/new:epsim.slot_info [1, DT1, 11]
  - !!python/object/new:epsim.slot_info [1, DT2, 12]
  SX:
  - !!python/object/new:epsim.slot_info [1, SX1, 7]
  - !!python/object/new:epsim.slot_info [1, SX2, 8]
  - !!python/object/new:epsim.slot_info [2, SX3, 19]
  - !!python/object/new:epsim.slot_info [2, SX4, 20]
  E:
  - !!python/object/new:epsim.slot_info [2, E, 23]

SLOT_COLORS:
  S: [255, 255, 255]
  DN: [105, 55, 255]
  DT: [255, 255, 0]
  SX: [5, 55, 255]
  E: [55, 55, 55]