START: 1
END: 15
CRANES:
- !!python/object/new:epsim.crane_info [ 1, H1, 1, 0.5, 1, 7, 1, 2]
- !!python/object/new:epsim.crane_info [ 2, H2, 1, 0.5, 8, 15, 8, 2]
JOBS: {P1: 1,P2: 2}
PROCS:
  P1:
  - !!python/object/new:epsim.op_info [S, 1, 0]
  - !!python/object/new:epsim.op_info [DN, 80, 5]
  - !!python/object/new:epsim.op_info [T, 1, 0]
  - !!python/object/new:epsim.op_info [SX, 80, 2]
  - !!python/object/new:epsim.op_info [E, 1, 0]
  P2:
  - !!python/object/new:epsim.op_info [S, 1, 0]
  - !!python/object/new:epsim.op_info [DT, 40, 5]
  - !!python/object/new:epsim.op_info [T, 1, 0]
  - !!python/object/new:epsim.op_info [SX, 80, 2]
  - !!python/object/new:epsim.op_info [E, 1, 0]
SLOTS:
  S:
  - !!python/object/new:epsim.slot_info [1, S, 1]
  DN:
  - !!python/object/new:epsim.slot_info [1, DN1, 3]
  - !!python/object/new:epsim.slot_info [1, DN2, 4]
  DT:
  - !!python/object/new:epsim.slot_info [1, DT1, 5]
  T:
  - !!python/object/new:epsim.slot_info [1, T1, 7]
  - !!python/object/new:epsim.slot_info [2, T2, 8]
  SX:
  - !!python/object/new:epsim.slot_info [2, SX1, 11]
  - !!python/object/new:epsim.slot_info [2, SX2, 12]
  E:
  - !!python/object/new:epsim.slot_info [2, E, 15]
SLOT_COLORS:
  S: [255, 255, 255]
  DN: [105, 55, 255]
  DT: [255, 255, 0]
  SX: [5, 55, 255]
  E: [55, 55, 55]